import React from 'react';
import { ServicesSection } from '@/components';

export const metadata = {
  title: 'Our Services - Dr. Abdul Kader',
  description: 'Generated by create next app',
};

export default function Page() {
  return (
    <>
      <ServicesSection />
    </>
  );
}
