import React from 'react';
import { Auth } from '@/components';

export const metadata = {
  title: 'Sign in or Create a new account - Dr. Abdul Kader',
  description: 'Generated by create next app',
};

export default function Page() {
  return (
    <>
      <Auth />
    </>
  );
}
