import React from 'react';
import { AllAppointments } from '@/components';

export const metadata = {
  title: 'All Appointments - Dr. Abdul Kader',
  description: 'Generated by create next app',
};

export default function Page() {
  return (
    <>
      <AllAppointments />
    </>
  );
}
