import { ContactsSection } from '@/components';
import React from 'react';

export const metadata = {
  title: 'Contacts - Dr. Abdul Kader',
  description: 'Generated by create next app',
};

export default function Page() {
  return (
    <>
      <ContactsSection />
    </>
  );
}
