import React from 'react';
import { AllReviews } from '@/components';

export const metadata = {
  title: 'All Reviews - Dr. Abdul Kader',
  description: 'Generated by create next app',
};

export default function Page() {
  return (
    <>
      <AllReviews />
    </>
  );
}
