import React from 'react';
import { AllUsers } from '@/components';

export const metadata = {
  title: 'All Users - Dr. Abdul Kader',
  description: 'Generated by create next app',
};

export default function Page() {
  return (
    <>
      <AllUsers />
    </>
  );
}
