import React from 'react';
import { AboutSection } from '@/components';

export const metadata = {
  title: 'About me - Dr. Abdul Kader',
  description: 'Generated by create next app',
};

export default function Page() {
  return (
    <>
      <AboutSection />
    </>
  );
}
