import React from 'react';
import { NewService } from '@/components';

export const metadata = {
  title: 'Add New Service - Dr. Abdul Kader',
  description: 'Generated by create next app',
};

export default function Page() {
  return (
    <>
      <NewService />
    </>
  );
}
