import React from 'react';
import { UpdatePassword } from '@/components';

export const metadata = {
  title: 'Update Password - Dr. Abdul Kader',
  description: 'Generated by create next app',
};

export default function Page() {
  return (
    <>
      <UpdatePassword />
    </>
  );
}
