import React from 'react';
import { Profile } from '@/components';

export const metadata = {
  title: 'My Profile - Dr. Abdul Kader',
  description: 'Generated by create next app',
};

export default function Page() {
  return (
    <>
      <Profile />
    </>
  );
}
