import React from 'react';
import { UpdateUser } from '@/components';

export const metadata = {
  title: 'Update User - Dr. Abdul Kader',
  description: 'Generated by create next app',
};

export default function Page() {
  return (
    <>
      <UpdateUser />
    </>
  );
}
