import { Navbar, Footer } from '@/components';
import '../styles/globals.css';
import { GlobalProvider } from '@/provider/GlobalProvider';

export const metadata = {
  title: 'Dr. Abdul Kader',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className='flex flex-col min-h-screen overflow-x-hidden'>
        <GlobalProvider>
          <Navbar />
          {children}
          <Footer />
        </GlobalProvider>
      </body>
    </html>
  );
}
