import { EmptyState } from '@/components';
import Head from 'next/head';

export const metadata = {
  title: 'Ooops! Something went wrong!!',
  description: 'Generated by create next app',
};

export default function NotFound() {
  return (
    <>
      <title>Ooops! Something went wrong!!</title>
      <EmptyState />
    </>
  );
}
