import React from 'react';
import { PricesSection } from '@/components';

export const metadata = {
  title: 'Our Prices - Dr. Abdul Kader',
  description: 'Generated by create next app',
};

export default function Page() {
  return (
    <>
      <PricesSection />
    </>
  );
}
