import React from 'react';
import { AllPrices } from '@/components';

export const metadata = {
  title: 'All Prices - Dr. Abdul Kader',
  description: 'Generated by create next app',
};

export default function Page() {
  return (
    <>
      <AllPrices />
    </>
  );
}
