import React from 'react';
import { AllServices } from '@/components';

export const metadata = {
  title: 'All Services - Dr. Abdul Kader',
  description: 'Generated by create next app',
};

export default function Page() {
  return (
    <>
      <AllServices />
    </>
  );
}
