import React from 'react';
import { UpdateService } from '@/components';

export const metadata = {
  title: 'Update Service - Dr. Abdul Kader',
  description: 'Generated by create next app',
};

export default function Page() {
  return (
    <>
      <UpdateService />
    </>
  );
}
