import React from 'react';
import { NewPrice } from '@/components';

export const metadata = {
  title: 'Add New Price - Dr. Abdul Kader',
  description: 'Generated by create next app',
};

export default function Page() {
  return (
    <>
      <NewPrice />
    </>
  );
}
