import React from 'react';
import { Appointments } from '@/components';

export const metadata = {
  title: 'My Appointments - Dr. Abdul Kader',
  description: 'Generated by create next app',
};

export default function Page() {
  return (
    <>
      <Appointments />
    </>
  );
}
