import React from 'react';
import { UpdatePrice } from '@/components';

export const metadata = {
  title: 'Update Price - Dr. Abdul Kader',
  description: 'Generated by create next app',
};

export default function Page() {
  return (
    <>
      <UpdatePrice />
    </>
  );
}
